### ISSUE TITLE
OSS License

### ISSUE THREAD

**Issue by ymotongpoo** [ErkHal/PRKL30#2]
Do you have any plans to attache the OSS license for this? I'm interested in this and would love to have the explicit OSS license.

**Comment by ErkHal** [comment]
Good point. I'll check with the other contributors and we'll decide on an open license.

**Comment by ErkHal** [comment]
https://github.com/ErkHal/PRKL30/blob/master/LICENSE

MIT License now added, feel free to use this project :) 
If you end up doing something awesome with these sources, please share it with us ! We'd love to hear what you end up doing with the project :)
